name: CI Security Pipeline

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Run static analysis (Semgrep)
        run: |
          pip install semgrep
          semgrep --config auto .
        working-directory: ./app

      - name: Run dependency audit
        run: npm audit --audit-level=high
        working-directory: ./app
